Glimesh/janus-ftl-plugin

AudioCodec.h
FtlStream.cpp
FtlStream.h
IngestConnection.cpp
IngestConnection.h
JanusFtl.cpp
VideoCodec.h

This change makes some small improvements to attribute parsing during ingest. Audio/video codec, ssrc, payload type, etc. are actually parsed and communicated to the `FtlStream` to process against incoming media packets instead of hard-coded values. Some rudimentary validation is also performed when the client attempts to begin streaming.
A change was also made to the SDP payload to resolve an issue with Firefox failing to decode the video stream.

📬 Improve attribute parsing and parse sender report packets

---

AudioCodec.h
FtlStream.cpp
FtlStream.h
FtlStreamStore.cpp
FtlStreamStore.h
JanusFtl.cpp
JanusFtl.h
VideoCodec.h

This change allows for sessions to complete a watch request for a channel ID that does not yet have a stream started. These sessions will be put into a 'pending' state until a stream is available with the given channel ID.
Sessions that exist when a stream has ended will also be put into this 'pending' state until the session ends or the channel ID starts a new stream.
This change also includes a fix for #5.

👀 Handle pending sessions gracefully

---

.gitignore
FtlStream.cpp
FtlStream.h
FtlStreamStore.cpp
FtlStreamStore.h
JanusFtl.cpp
JanusFtl.h
JanusSession.cpp
JanusSession.h
RelayThreadPool.cpp
RelayThreadPool.h
RtpRelayPacket.h
meson.build

This change introduces a new `RelayThreadPool` class to handle taking incoming packets from `FtlStream` objects and relaying them to associated `JanusSession` viewers without clogging up the `FtlStream` thread and delaying new packets from being processed.

🧵 Introduce thread pool model for relaying packets

---

FtlRtp.h
FtlStream.cpp
FtlStream.h
FtlStreamStore.cpp
IngestConnection.cpp
IngestConnection.h
IngestServer.cpp
RelayThreadPool.cpp

This PR contains the following changes:
- Adds typedefs for some common RTP and FTL fields to help readability.
- Incoming FTL media packets that come from an IP address other than that of the initial ingest handshake will be rejected.
- Rudimentary logic to send NACK requests to FTL clients for packets that appear to have been lost.

📩 Add NACK support for incoming streams

---

FtlStream.cpp
FtlStream.h
JanusFtl.cpp
JanusFtl.h
JanusSession.h
Keyframe.h

This change introduces caching of keyframes by `FtlStream`, plus sending of those keyframes to viewers when a new viewer connects (so they get an immediate image), as well as when a [picture-loss-indication](https://tools.ietf.org/html/rfc4585#section-6.3.1) is received to assist in recovering of lost data needed to decode the video stream.
Further stream stability can likely be achieved by implementing forward error correction (tracked in #14).
This also caches the needed data to generate thumbnail images (tracked in #16).

🖼 Cache keyframes, and send them to viewers in response to PLI feedback

---

meson.build

Neglected to add the libraries and defines needed to enable HTTPS in the [cpp-httplib](https://github.com/yhirose/cpp-httplib) being used for the `GlimeshServiceConnection`.

💥 Fix build to include libraries and defines needed for HTTPS

---

FtlStream.h

Should fix #24 where we were seeing some garbage values come in due to them being improperly initialized.

🚮 Initialize metadata values to zero to prevent garbage

---

FtlStream.cpp
RelayThreadPool.cpp
RelayThreadPool.h

Two-in-one special!
1. Fixed an instance where we were reading data from a location that had already been free'd.
2. Joined relay threads when the relay thread pool is being stopped rather than just hoping they end themselves before the process goes down.
Fixes #15 
This change also sets the number of default relay threads to the value returned by [`std::thread::hardware_concurrency`](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency), which should get us close to the most efficient number of threads to run on a particular machine.

🖇 Fix a reference to free'd memory, properly spin down relay threads

---

GlimeshServiceConnection.cpp
IngestServer.cpp

`json_pack` was taking ownership of the reference to our `JsonPtr variables` and freeing it on our behalf, so when we ended up freeing `variables` we'd hit a double free and occasional crash.
This change fixes that issue by using the identifier `O` instead of `o` to indicate to `json_pack` that it should only increment the ref count, not steal the reference.
There are also a couple of small valgrind fixes, initializing structs to 0 so we don't reference uninitialized bytes anywhere.
Additional logging was added to the access token expiration time logic, since we've been seeing issues where access tokens are being renewed too often.

💣 Fixed another JSON double free in `GlimeshServiceConnection`

---

.github/workflows/build.yml
Configuration.cpp
Configuration.h
Dockerfile
DummyServiceConnection.cpp
DummyServiceConnection.h
FtlExceptions.h
FtlStream.cpp
FtlStream.h
GlimeshServiceConnection.cpp
GlimeshServiceConnection.h
H264PreviewGenerator.cpp
H264PreviewGenerator.h
JanusFtl.cpp
LibAvCodecPtr.h
PreviewGenerator.h
README.md
ServiceConnection.h
meson.build

This change adds the `PreviewGenerator` abstraction which represents a class that can generate previews for a given FTL stream. Right now, it exposes just one method, `GenerateJpegImage(Keyframe)`. There is only one implementation of this class, and that is `H264PreviewGenerator` for H264 streams.
`ServiceConnection` has been updated with a new method, `SendJpegPreviewImage(streamId, jpegData)`, meant to transmit the jpeg preview image to the given service connection. The `GlimeshServiceConnection` will transmit the jpeg data to Glimesh via a GraphQL query, whereas the `DummyServiceConnection` will write the jpeg data to a local file in the directory indicated by the `FTL_SERVICE_DUMMY_PREVIEWIMAGEPATH` env var (`~/.ftl/previews` by default).
`FtlExceptions.h` has been added and populated …

📷 Add thumbnail support, plus retry logic to GlimeshServiceConnection

---

LICENSE
README.md

This change updates the license of the project from GPLv3 to AGPLv3.
As this software is primarily a network service, it's important to ensure that the open source nature of the project is preserved even if "distribution" occurs via communication to the software over a network server rather than distribution of the software binaries. The AGPL includes some additional provisions over the GPL that allow us to ensure this.

📃 Update license to AGPLv3

---

Configuration.cpp
Configuration.h
DummyServiceConnection.cpp
DummyServiceConnection.h
JanusFtl.cpp
README.md

Currently when using the dummy service connection the hmac key is hard coded as `aBcDeFgHiJkLmNoPqRsTuVwXyZ123456`.
This change
Changes:
- Allow overriding the key with the environment variable `FTL_SERVICE_DUMMY_HMAC_KEY` so local testing can both be more realistic and more secure
- Update README documentation of the new env variable

🔐 Add env override for dummy hmac key

---

Dockerfile
FtlStream.cpp

Always nice to upgrade to the latest Ubuntu LTS, and at least for me this makes the H264 decoder work in the Docker image.
Previously I would continuously see the following printed:
```
[ERR] [../FtlStream.cpp:startStreamMetadataReportingThread:438] FTL: Failed to generate JPEG preview for stream 1, error: Could not find H264 codec![ERR] [../FtlStream.cpp:startStreamMetadataReportingThread:438] FTL: Failed to generate JPEG preview for stream 1, error: Could not find H264 codec![ERR] [../FtlStream.cpp:startStreamMetadataReportingThread:438] FTL: Failed to generate JPEG preview for stream 1, error: Could not find H264 codec![ERR] [../FtlStream.cpp:startStreamMetadataReportingThread:438] FTL: Failed to generate JPEG preview for stream 1, error: Could not find H264 codec![ERR] …
```

⬆️ Update base image in Dockerfile

---

IngestConnection.cpp
IngestServer.cpp

Fixes #18
Tested locally by connecting/disconnecting multiple clients while also starting/stopping streaming.
Verified via `ls -l /proc/{pid}/fd` that the number of open file descriptors does not keep growing and growing with this change.

🛑 Properly close connections

---

.gitignore
.gitmodules
README.md
meson.build
src/Configuration.cpp
src/Configuration.h
src/DummyServiceConnection.cpp
src/DummyServiceConnection.h
src/EdgeNodeServiceConnection.cpp
src/EdgeNodeServiceConnection.h
src/FtlClient.cpp
src/FtlClient.h
src/FtlStream.cpp
src/FtlStream.h
src/FtlStreamStore.cpp
src/FtlStreamStore.h
src/IngestConnection.cpp
src/IngestConnection.h
src/JanusFtl.cpp
src/JanusFtl.h
src/RelayThreadPool.cpp
src/Result.h
src/Util.h
src/ftlclienttest.cpp
subprojects/fmt.wrap
subprojects/spdlog.wrap

This change is the first iteration of work enabling Janus-FTL to scale across multiple servers to distribute load.
This is achieved by communicating with another service, [janus-ftl-orchestrator](https://github.com/Glimesh/janus-ftl-orchestrator).
The Orchestrator service will determine which streams should be relayed where and direct various janus-ftl-plugin instances on when and where to relay their video bits accordingly. For more on this, read the documentation in the [janus-ftl-orchestrator](https://github.com/Glimesh/janus-ftl-orchestrator) repository.
At a high level, this change does the following:
- Adds `janus-ftl-orchestrator` as a git submodule so that the client header-only library `FtlOrchestrationClient` can be consumed.
- Options for configuring the Orchestrator connection …

🚦 Allow relaying of FTL streams via Orchestrator

---

.gitmodules

You can't checkout `git` paths unless you have a key registered in GitHub. We either need to change it to the https format, or use an approach like this for git to automatically select the path needed: https://github.com/Glimesh/glimesh.tv/blob/d5d67b2a5722dffbe1487d1452fbb3dd49d89ee3/.gitmodules

Fixing checkout for https guests

---

src/JanusFtl.cpp

When an Edge node subscribes to a stream, it generates a temporary stream key that other nodes can use to relay that stream to the Edge.
An oversight in #50 left temporary stream keys in memory even after they were no longer needed.
This change removes temporary stream keys when the Edge node unsubscribes from that channel.

🔑 Remove temporary stream keys when unsubscribing

---

.dockerignore
Dockerfile
README.md

Have yet to test janus still works but it at least still compiles.
Once I test I'll update this and update the readme so #32 can be called complete.

Docker cleanup

---

src/JanusFtl.cpp

Silly me forgot to increment an iterator, causing an infinite loop when attempting to stop relays on stream end.
Fixes #63

🔁 Fix infinite loop when stopping relays

---

src/ConnectionListeners/TcpConnectionListener.cpp
src/FtlStream.cpp
src/JanusFtl.cpp
src/JanusSession.cpp

Leftovers of moving from `JANUS_LOG` to `spdlog` - fixing some bad log formatting in a few areas, and a few leftover `JANUS_LOG` statements.
Fixes #62

📃 Logging cleanup

---

src/ServiceConnections/GlimeshServiceConnection.cpp

Update `GlimeshServiceConnection` to new stream key query format as defined by https://github.com/Glimesh/glimesh.tv/pull/430

🔐 Update Glimesh stream key query

---

src/FtlControlConnection.cpp
src/FtlServer.cpp

Fixes #69 
The `FtlControlConnection::onStartMediaPort` callback would sometimes lead to a crash due to `FtlServer` prematurely removing the `FtlControlConnection` from the pending connection store - if an error occurs during stream negotiation inside of `FtlServer::onControlStartMediaPort` (such as the service connection refusing the StartStream request), the `FtlControlConnection` instance would be destructed before it is able to handle the error.
Fixed by waiting to remove the `FtlControlConnection` from the pending connection store until the control connection has successfully been handed off to `FtlStream`.

▶💥 Fix seg fault after failed service connection StartStream

---

src/FtlControlConnection.cpp
src/FtlServer.cpp
src/FtlServer.h
src/FtlStream.cpp
src/JanusFtl.cpp

This change introduces a 5000ms timeout for any incoming ingest connections that don't pass HMAC authentication.
Also a bit of cleanup around `FtlServer::Stop` and some log messages.
Fixes #68

⏱ Time out ingest connections that don't authenticate

---

README.md
src/Configuration.cpp
src/Configuration.h
src/JanusFtl.cpp
src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h

Adds a new environment variable `FTL_SERVICE_REST_PATH_BASE` (defaults to `/`) that controls the base path for all REST service API calls. Previously any REST API that wished to serve Janus FTL was required to have the routes at the base of the application. This allows the API handler to serve at a deeply nested path. The default value of `/` retains the same behavior as before.
The input from `FTL_SERVICE_REST_PATH_BASE` is sanitized so leading and trailing `/` characters are normalized. For example: `/api/`, `/api`, `api/`, and `api` all will all resolve to the same path of `http://example.com/api/...`

Add configurable base path for REST service API calls

---

src/ConnectionTransports/ConnectionTransport.h
src/ConnectionTransports/NetworkSocketConnectionTransport.cpp
src/ConnectionTransports/NetworkSocketConnectionTransport.h
src/FtlControlConnection.cpp
src/FtlServer.cpp

Fixes #74 
Before this fix, `FtlControlConnection::stopConnection(...)` would call `Stop()` on its underlying `NetworkSocketConnectionTransport`, which in turn would wait for its underlying read thread to exit. Problem is, the original call to `stopConnection(...)` was triggered by the `NetworkSocketConnectionTransport` read thread, resulting in a deadlock as the thread waits for itself to exit.
This change adds a `noBlock` parameter to `ConnectionTransport::Stop(...)`, allowing callers to indicate that it should not block on the exiting of the transport read thread. `FtlControlConnection::stopConnection(...)` uses this parameter to avoid the deadlock.
In the future it might make sense to add a separate "dispatch" thread to `NetworkSocketConnectionTransport` so callbacks aren't tied to …

⌛ Fix deadlock on FtlControlConnection::stopConnection

---

README.md
src/Configuration.cpp
src/Configuration.h
src/ConnectionTransports/NetworkSocketConnectionTransport.cpp
src/ConnectionTransports/NetworkSocketConnectionTransport.h
src/FtlControlConnection.cpp
src/FtlControlConnection.h
src/JanusFtl.cpp
src/JanusFtl.h

Fixes #42
This change introduces the `FTL_MAX_ALLOWED_BITS_PER_SECOND` configuration, providing a means of restricting the maximum bandwidth any given stream is allowed to consume before it is kicked off the server.
There are a few other changes in this payload as well:
- `FtlControlConnection::FtlResponseCode` enum is introduced (from [ftl-sdk](https://github.com/microsoft/ftl-sdk/blob/d0c8469f66806b5ea738d607f7d2b000af8b1129/libftl/ftl_private.h#L365-L385)), and is now referenced instead of hard-coded string values throughout `FtlControlConnection`.
- Better locking mechanisms around `NetworkSocketConnectionTransport`'s stopping procedure to prevent getting into a deadlocked state if the server is trying to stop a stream around the same time a client is.
An issue #79 was also discovered …

🌊 Enable restricting max bandwidth of incoming streams

---

src/ServiceConnections/GlimeshServiceConnection.cpp
src/ServiceConnections/GlimeshServiceConnection.h
src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h

This change updates us to `v0.8.4` of [cpp-httplib](https://github.com/yhirose/cpp-httplib), which includes a decent number of fixes to bugs that I suspect may be causing some of our HTTPS request failures we're seeing in production.
As a result of some of the changes in the httplib update, a few changes were made to the ServiceConnection implementations to avoid copying of `httplib::Client` and `httplib::Result` instances (they are now backed by `unique_ptr`).
Additional logging detail was also added in the Glimesh HTTP request failure case so we can determine root cause if this doesn't resolve the failures.
Verified by testing against local glimesh.tv instance.

📚 Update cpp-httplib, plus additional logging on failed HTTP requests

---

src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h

Fixes a crash in the RestServiceConnection that was introduced by #81
The member initializer list was attempting to initialize the `httpClient` member with other member values that had not yet been initialized themselves.
Did a little bit of cleanup as well, replacing `stringstream` with `fmt::format`.

💤 Fix crash in REST service connection

---

src/ConnectionTransports/NetworkSocketConnectionTransport.cpp

While a zero-length read on a non-blocking TCP socket indicates the client has closed the connection, it does not mean the same for UDP, where zero-length packets are allowed.
Sometimes the FTL client will choke up a bit if the machine is under load and send a few empty UDP packets - we don't want to close their connection in this case. Discovered this while load testing.

0️⃣ Allow zero length UDP socket reads

---

src/JanusFtl.cpp
src/ServiceConnections/DummyServiceConnection.cpp
src/ServiceConnections/DummyServiceConnection.h
src/ServiceConnections/EdgeNodeServiceConnection.cpp
src/ServiceConnections/EdgeNodeServiceConnection.h
src/ServiceConnections/GlimeshServiceConnection.cpp
src/ServiceConnections/GlimeshServiceConnection.h
src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h
src/ServiceConnections/ServiceConnection.h

This change updates the `GlimeshServiceConnection` to properly respond to changes introduced here: https://github.com/Glimesh/glimesh.tv/pull/483
If a GraphQL error is returned by the service while updating metadata for a stream, that stream will be stopped.
This serves as a mechanism for the service to shut down currently running streams.

🔪 Kill streams on metadata report error

---

src/ServiceConnections/GlimeshServiceConnection.cpp

Access token was still being logged, number of format slots was changed but not the arguments.
ex:
```
[2021-02-27 00:42:27.912] [info] Received new access token, expires in ee8f831cfa0d45a7675ca65c0df6daa9be95681ad185f0a408d40a0c45b6bf32 - 1614462965 = 1614415347 seconds
```

Update logging in GlimeshServiceConnection.cpp

---

src/FtlClient.cpp

This fixes an issue that would occur when an FtlClient control connection was closed where the client would spin indefinitely trying to read the socket.

🎡 FtlClient spin lock fix

---

src/FtlClient.h

Fixing what I assume was a leftover debugging value - the FtlClient now waits 1 second before timing out instead of 500 seconds.

⌛ Set FtlClient connection timeout value to something more sane

---

src/FtlStream.cpp

We're seeing issues where on RTP sequence number rollover, we mark an enormous packet range as "lost".
To expedite production stability, we're disabling this feature entirely until the issue can be resolved. #95

🛑 Disable NACKs until bug can be addressed

---

.github/workflows/build.yml
README.md
meson.build
meson_options.txt
src/Configuration.cpp
src/Configuration.h
src/JanusFtl.cpp
src/JanusFtl.h
src/Utilities/Watchdog.cpp
src/Utilities/Watchdog.h

Support for optional systemd watchdog integration to automatically restart the service if it is deadlocked. For context see http://0pointer.de/blog/projects/watchdog.html
Compile time support is auto enabled if you have the systemd dev headers available (Ubuntu package `libsystemd-dev`). Runtime support is auto enabled if you set the `WatchdogSec` systemd service option, this causes `WATCHDOG_USEC` to be passed which enables this watchdog integration.
Please be generous with the value for `WatchdogSec`. Strictly speaking the recommendation is to ping exactly every `WATCHDOG_USEC / 2`. To keep things simple I instead ping from the metadata reporting thread once per loop it does. This loop can take a variable amount of time as it does a lot of work. It loops through all streams to calculate …

⌚🐕 Watchdog support

---

src/ServiceConnections/GlimeshServiceConnection.cpp
src/ServiceConnections/GlimeshServiceConnection.h
src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h

We've been seeing some strange crashes that looked like memory corruption.
After some hunting around we think we've narrowed it down to using the class instance of `httplib::Client` from multiple threads in parallel.
Technically the client does have a request mutex, but that has two limitations:
1. Changing headers is not protected by the request mutex, we think this is leading to the memory corruption.
2. Only one request may be in-flight at a time with a single client, this is probably adding significant latency in some cases
The downside of this is that we establish a new connection for basically every request, but I think the latency that can add is minimal compared to the above downsides.
Verified the GlimeshServiceConnection still works using my homelab setup.

❣️ Fix use-after-free bug from using httplib::Client in non-thread-safe ways

---

.gitmodules
meson.build
src/ConnectionListeners/ConnectionListener.h
src/ConnectionListeners/TcpConnectionListener.cpp
src/ConnectionListeners/TcpConnectionListener.h
src/FtlControlConnection.cpp
src/FtlControlConnection.h
src/FtlServer.cpp
src/FtlServer.h
src/FtlStream.cpp
src/FtlStream.h
src/JanusFtl.cpp

This change introduces a single-thread event queue model for `FtlServer` in order to minimize issues with deadlocks and out-of-order processing for sequential events.
`FtlServer` now contains definitions for 11 events that can be processed:
```cpp
enum class FtlServerEventKind
{
Unknown = 0,
StopStream,                 // Request to stop a specific Channel / Stream ID
NewControlConnection,       // ConnectionListener has produced a ConnectionTransport
ControlConnectionClosed,    // FtlControlConnection has closed
ControlRequestHmacKey,      // Control connection requests HMAC key
ControlHmacKeyFound,        // HMAC key has been provided for a Control connection
ControlRequestMediaPort,    // Control connection requests media port
TerminateControlConnection, // Terminate and remove a …
```

📬 FtlServer event queue model

---

.gitignore
src/FtlStream.cpp
src/FtlStream.h
src/JanusFtl.cpp
src/JanusFtl.h
src/PreviewGenerators/H264PreviewGenerator.cpp
src/ServiceConnections/GlimeshServiceConnection.cpp
src/ServiceConnections/GlimeshServiceConnection.h
src/ServiceConnections/RestServiceConnection.cpp
src/ServiceConnections/RestServiceConnection.h

Splitting this off from what I'm working on.
No functional change, just handy because it compiles twice as fast and has better error messages.
test with `CC=clang CXX=clang++ meson build-clang && ninja -C build-clang`

💨 Support compiling with clang

---

meson.build

I meant to make systemd an optional dependency, but I used meson's `disabler()` which actually recursively disables any parts of the build it is included in. So the main `.so` would not build if you didn't have libsystemd-dev installed.
Fixes #103

💩 Do not disable build if systemd is missing

---

meson.build
src/FtlControlConnection.h
src/FtlServer.cpp
src/FtlServer.h
src/FtlStream.cpp
src/FtlStream.h
src/JanusFtl.cpp
src/JanusFtl.h
src/JanusStream.cpp
src/JanusStream.h
src/RtpPacketSink.h

Going back and doing ebefe001a1f6a42cac2c1c8f7cf59db18fe50897 the right way this time.
This shortens the path for RTP packets to only require a single lock at the stream level.

📦 Hand RTP packets directly to JanusStream

---

src/FtlControlConnection.cpp

🕑 Use constant time compare for HMAC check

---

src/FtlStream.cpp

This ping is not expected to be used by the server, it is meant to be ponged back to the client as part of measuring RTT.
Now it's true the client only uses this right now to do a bandwidth test it then ignores, but it does log the bandwidth so it'd be nice for debugging to have the numbers be accurate (right now the client defaults to a two second RTT because it never gets a pong to measure)
See https://github.com/Glimesh/ftl-sdk/blob/5912733506c066684aebd43f3e0b94cf51ca98c1/libftl/media.c#L1165-L1174

🏓 Ping handling for FTL media streams

---

src/FtlClient.cpp
src/FtlClient.h

We noticed last night that there is a race condition in FtlClient that can lead to a double close of a socket, for now protecting with a mutex following an identical pattern to what NetworkSocketConnectionTransport does.
Verified locally by refreshing a single viewer several times to stop/create new edge ftl clients.
Might help with #115

🔐 Add stopping lock to FtlClient

---

src/JanusFtl.cpp

Per https://tools.ietf.org/html/rfc7587#section-6.1 if the sender does not specify `sprop-stereo=1` the receiver may default to downmixing stereo sources to mono.
Firefox does this: https://bugzilla.mozilla.org/show_bug.cgi?id=1524145

🔊 Ask receiver to play stereo audio

---

src/FtlStream.cpp
src/FtlStream.h

Pretty straightforward and small change I made while working on some other stuff.
Did test the NACK sent was correct.

♻️ Extract `sendNack` method

---

.github/workflows/build.yml
meson.build
pch/janus_ftl_test_pch.h
src/FtlControlConnection.cpp
src/FtlControlConnection.h
src/FtlControlConnectionManager.h
src/FtlServer.h
src/FtlStream.cpp
src/Utilities/Util.h
test/mocks/MockConnectionTransport.h
test/mocks/MockFtlControlConnectionManager.h
test/test.cpp
test/unit/FtlControlConnectionUnitTests.cpp

Introduces the following changes:
- `FtlControlConnectionManager` interface introduced to abstract callbacks from `FtlControlConnection` (such as `ControlConnectionStopped`, `ControlConnectionRequestedHmacKey`, etc. `FtlServer` implements this interface.
- `MockFtlControlConnectionManager` introduced to facilitate unit testing of `FtlControlConnection`
- `MockConnectionTransport` introduced to facilitate unit testing of any class that uses `ConnectionTransport` classes.
- Various PCH/build changes to improve build of test binary
- `FtlControlConnectionUnitTests.cpp` added with a simple text fixture and test case verifying the FTL connection handshake is processed correctly by `FtlControlConnection`
- GitHub action added to run test binary for validation.

🧪 Add FtlControlConnectionTest, add GH action for tests
